# Generated by Django 3.1.2 on 2020-12-31 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='extra',
            field=models.CharField(db_index=True, default=None, blank=True, null=True, max_length=20),
        ),
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(db_index=True, default=None, blank=True, null=True, max_length=20),
        ),
        migrations.AddField(
            model_name='address',
            name='type',
            field=models.CharField(db_index=True, default=None, blank=True, null=True, max_length=20),
        ),
        migrations.AddField(
            model_name='address',
            name='hash',
            field=models.CharField(db_index=True, default=None, blank=True, null=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_number',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('locality', 'route', 'street_number', 'extra')},
        ),
    ]
